package com.dialer.domain.repository


/*** This  Interface is useful for handling the all the events generated by the end users  for the Ui interface
 *   1 These all methods are triggered  by the user to interact with the call
 *   for eg accept the incoming call reject the call or the turn off and  on the speaker mode
 *
 * ***/
interface DialerUserActionEvents {

    fun acceptCall(number: String)
    fun rejectCall(number: String)
    fun holdCall(number: String)
    fun swapCall(number: String)
    fun changeSpeakerPhoneState(state: Int)



}